proyecto/apps/cliente/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import home,crear_clientes,crear_form,busqueda,templante,productoCategoria
app_name='cliente'
urlpatterns = [
    path("" ,home, name="home" ),
    path("clientes_creados/",crear_clientes,name="crear_clientes"),
    path("crear/", crear_form,name="crear"),
    path("busqueda/",busqueda,name="busqueda"),
    path("templates/",templante,name="template"),
    path("productosCategoria/list",productoCategoria,name="productoCategoria_list" )
]
urlpatterns += staticfiles_urlpatterns()

proyecto/apps/usuario/urls.py
from django.urls import path
from .views import funcion
urlpatterns = [    
    path('', funcion  ,name="funcion")
]

proyecto/config/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('saludar/',views.saludo),
    path('segundoSaludo/', views.segundoSaludo),
    path('nombre/<nombre>/<apellido>', views.nombre),
    path('probando_template/', views.template),
    path('hora/',views.fecha_hora),
    path('notas/', views.mis_notas),
    path('nombres/',views.template),
    path('',include("cliente.urls")),
    path('usuario/',include("usuario.urls"))
]

proyecto/apps/cliente/models.py
from django.db import models

# Create your models here.
class Pais(models.Model):
    nombre = models.CharField(max_length=50)
    def __str__(self) -> str:
        return self.nombre

class Cliente(models.Model):
    nombre= models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    nacimiento = models.DateField(null=True)
    pais_origen_id=models.ForeignKey(Pais, on_delete= models.SET_NULL,null=True , blank=True)
    
    def __str__(self) -> str:
        return f"{self.nombre} , {self.apellido},{self.nacimiento}"
    
class ProductoCategoria(models.Model):
    nombre = models.CharField(max_length=50,unique=True)
    descripcion =  models.TextField(max_length=250,null=True,blank=True,verbose_name="descripción")
    
    def __str__(self) -> str:
        return self.nombre

    class Meta:
        verbose_name="categoría de productos"

proyecto/apps/usuario/models.py
from django.db import models

# Create your models here.

proyecto/apps/cliente/forms.py
from django import forms 

from .models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ["nombre","apellido","nacimiento","pais_origen_id"]

proyecto/apps/cliente/views.py
from django.shortcuts import render,redirect
from .models import Pais,Cliente
from .forms import ClienteForm
from django.http import HttpRequest,HttpResponse
from datetime import date
from . import models
# Create your views here.

def home(request):
    clientesRegistrados = Cliente.objects.all()
    contexto = {"clientes" : clientesRegistrados}
    #return render (request,"index.html" , {"clientes" : clientesRegistrados})
    return render(request,"cliente/index.html" , contexto)

def crear_clientes(request):
    from datetime import date
    p1 = Pais(nombre = "Arg")
    p2 = Pais(nombre="Ch")
    p3 = Pais(nombre = "Mx")
    p1.save()
    p2.save()
    cliente1 = Cliente(nombre="rodrigo" , apellido = "Garcia " , nacimiento = date(1997,1,1) ,pais_origen_id=p1)
    cliente2 = Cliente(nombre = "Mati" , apellido= "Erusalimsky",nacimiento = date(1996,7,10) , pais_origen_id=p2 )


    cliente1.save()
    cliente2.save()
    return redirect("cliente:home")


def crear_form(request: HttpRequest) -> HttpResponse:
    
    if request.method == "POST":
        form =ClienteForm(request.POST)
        if form.is_valid():
            form.save()
    else :
        form = ClienteForm()
    return render(request,"cliente/crear.html",{"form":form})

def busqueda(request):
    cliente_nombre = Cliente.objects.filter(nombre__contains="o")
    cliente_nacimiento = Cliente.objects.filter(nacimiento__gt = date(2000,1,1))
    contexto = {
        "cliente_nombre": cliente_nombre,
        "cliente_nacimiento" : cliente_nacimiento
    }
    return render(request,"cliente/busqueda.html", contexto)

def templante(request):
    contexto = {"app" : "categoria productos"}
    return  render(request,'cliente/template2.html',contexto)

def productoCategoria(request):
    categorias = models.ProductoCategoria.objects.all()
    contexto = {"categorias":categorias}
    return render (request,"cliente/productoCategoria.html",contexto)

proyecto/apps/usuario/views.py
from django.shortcuts import render

# Create your views here.

def funcion(request):
    
    return render(request,"usuario/usuario.html")

proyecto/config/views.py
from django.http import HttpResponse
#from django.template import Context, Template 
from datetime import datetime
from django.shortcuts import render

def saludo(resquest):
    return HttpResponse ("Hola Django- Coder")  #httpResponse es una clase que va a devolver un string

def segundoSaludo(resquest):
    return HttpResponse("<h1> Esto es otra funcion</h1>")

def nombre(request,nombre : str,apellido : str):
    nombre = nombre.capitalize()
    apellido = apellido.capitalize()
    print(f"{apellido} ,{nombre} ")
    edad = input("Edad:")
    return HttpResponse(f"{apellido} , {nombre} : edad {edad}")

def template(request):
   # mi_html = open("./templates/template.html")
   # mi_template = Template(mi_html.read())
   # mi_html.close()
    nombre = "Rodrigo"
    apellido = "Garcia"
    ahora = datetime.now().strftime("%d/%m/%Y  %H:%M:S.%f")
    datos={"nombre": nombre , "apellido" : apellido , "fecha":ahora}
   # mi_contexto = Context(datos)
   # mi_documento = mi_template.render(mi_contexto)
   # return HttpResponse (mi_documento)
    return render(request,"template.html" , datos)

def fecha_hora(request):
    
    ahora = datetime.now().strftime("%d/%m/%Y  %H:%M:S.%f")
    return HttpResponse(f"<h1> Fecha y hora : {ahora} <h1>")


def mis_notas(request):
    lista_de_notas = [2,3,4,5,6,7,8,9]
    context = {"notas" : lista_de_notas}
    return render(request,"template2.html" , context)

def template(request):
    nombre= "Rodrigo"
    apellido="Garcia"
    numeros = [1,2,3,4,5,6,7,8,9]
    datos = {"nombre":nombre, "apellido":apellido,"numeros": numeros}
    return render(request,"template3.html",datos)
    

proyecto/apps/cliente/templates/cliente/busqueda.html
{% extends 'cliente/index.html' %}

{% block FORM %}
busqueda
{% endblock FORM %}
{% block CONTENIDO %}
  <h2> nombre del cliente </h2>
  {% for cliente in cliente_nombre  %}
    <p> {{cliente}} </p>
  {% endfor %}
{% block BUSQUEDA %}
{% for cliente in cliente_nacimiento %}
<p> {{cliente }} </p>
{% endfor %}
{% endblock BUSQUEDA %}
{% endblock CONTENIDO %}

proyecto/apps/cliente/templates/cliente/crear.html
{% extends 'cliente/index.html' %}

{% block FORM %}
crear cliente
{% endblock FORM %}
{% block CONTENIDO %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Guardar</button>
    </form>
{% endblock CONTENIDO %}

proyecto/apps/cliente/templates/cliente/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>Titulo</h1>
    <h2>  tu mama</h2>
    {% block CONTENIDO %}
    {% endblock CONTENIDO %}
    {% for cliente in clientes %}
    <p> {{cliente.nombre}} {{cliente.apellido}}</p>
    {% endfor %}
   {% block FORM %}
   {% endblock FORM %}
   {% block BUSQUEDA %}{% endblock BUSQUEDA %}
</body>
</html>

proyecto/apps/cliente/templates/cliente/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#!">{{titulo}}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="#">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'cliente:home' %}">inicio</a></li>
            </ul>
        </div>
    </div>
</nav>

proyecto/apps/cliente/templates/cliente/template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'cliente/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'cliente/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        {% block CONTENIDO %}
        {% endblock CONTENIDO %}
        <!-- Responsive navbar-->
        {% include 'cliente/nav.html' with titulo="titlo de la pagina" %}
        <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">el otro titulo</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Posted on January 1, 2023 by Start Bootstrap</div>
                            <!-- Post categories-->
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
                        </header>
                        <!-- Preview image figure-->
                        <figure class="mb-4"><img class="img-fluid rounded" src={% static 'cliente/img/capitan-america-age-of-ultron.jpg' %} alt="..." /></figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">Science is an enterprise that should be cherished as an activity of the free human mind. Because it transforms who we are, how we live, and it gives us an understanding of our place in the universe.</p>
                            <p class="fs-5 mb-4">The universe is large and old, and the ingredients for life as we know it are everywhere, so there's no reason to think that Earth would be unique in that regard. Whether of not the life became intelligent is a different question, and we'll see if we find that.</p>
                            <p class="fs-5 mb-4">If you get asteroids about a kilometer in size, those are large enough and carry enough energy into our system to disrupt transportation, communication, the food chains, and that can be a really bad day on Earth.</p>
                            <h2 class="fw-bolder mb-4 mt-5">I have odd cosmic thoughts every day</h2>
                            <p class="fs-5 mb-4">For me, the most fascinating interface is Twitter. I have odd cosmic thoughts every day and I realized I could hold them to myself or share them with people who might be interested.</p>
                            <p class="fs-5 mb-4">Venus has a runaway greenhouse effect. I kind of want to know what happened there because we're twirling knobs here on Earth without knowing the consequences of it. Mars once had running water. It's bone dry today. Something bad happened there as well.</p>
                        </section>
                    </article>
                    <!-- Comments section-->
                    <section class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
                                <!-- Comment with nested comments-->
                                <div class="d-flex mb-4">
                                    <!-- Parent comment-->
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                                        <!-- Child comment 1-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                            <div class="ms-3">
                                                <div class="fw-bold">Commenter Name</div>
                                                And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                                            </div>
                                        </div>
                                        <!-- Child comment 2-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                            <div class="ms-3">
                                                <div class="fw-bold">Commenter Name</div>
                                                When you put money directly to a problem, it makes a good headline.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Single comment-->
                                <div class="d-flex">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">Web Design</a></li>
                                        <li><a href="#!">HTML</a></li>
                                        <li><a href="#!">Freebies</a></li>
                                    </ul>
                                </div>
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">JavaScript</a></li>
                                        <li><a href="#!">CSS</a></li>
                                        <li><a href="#!">Tutorials</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Side Widget</div>
                        <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'cliente/js/scripts.js' %}"></script>
    </body>
</html>

proyecto/apps/cliente/templates/cliente/template2.html
{% extends 'cliente/template.html' %}
{% block CONTENIDO %}
<a href="{% url 'cliente:productoCategoria_list' %}">producto</a>
<a href="{% url 'cliente:template' %}"> boton </a>
{% endblock CONTENIDO %}

proyecto/apps/cliente/templates/productoCategoria.html
{% extends 'cliente/template2.html' %}

{% block CONTENIDO %}
{% if {{categorias}} %}

<p> hay elementos</p>
{% else %}
<p> no hay elementos </p> 
{% endif %}
<a href="{% url 'cliente:template' %}"> botoN </a>
{% endblock CONTENIDO %}

proyecto/apps/usuario/templates/usuario/usuario.html
{% extends 'usuario/usuario2.html' %}
{% block CONTENIDO %}
esto es un contenido de prueba
{% endblock CONTENIDO %}
{% block NUEVO %}
    
{% endblock NUEVO %}

proyecto/apps/usuario/templates/usuario/usuario2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> segndo usuario</h1>
    {% extends 'cliente/index.html' %}
    {% block CONTENIDO %}
    esto es un contenido de prueba
    {% endblock CONTENIDO %}
    <a href=" {% url 'cliente:usuario' %}"> ir a clientes </a>
    {% block NUEVO %}
    {% endblock NUEVO %}
</body>
</html> 

proyecto/templates/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> Esto es una Template</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia, in!</p>
    <h2>Esto sigue siendo un Template</h2>
    <ul>
        <li>El</li>
        <li>Cap</li>
        <li>America</li>
    </ul>
    <h3>Nombre:{{ nombre }}</h3>
    <h3>Apellido:{{ apellido }}</h3>
    <h3>Esto se abrio el {{ fecha }} </h3>
</body>
</html>

proyecto/templates/template2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Estas son mis notas</h1>
    {% for nota in notas %}

    {% if nota <= 4 %}   
        <p style="color: red;"> NOTA MALA : {{nota}} </p>
    {% else %}
        <p style="color: green;"> NOTA BUENA: {{nota}} </p>

    {% endif %}

    
    {% endfor %}
    
</body>
</html>

proyecto/templates/template3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="color: rgb(2, 2, 156); font-size: 30px;">  El titulo es : {{nombre}} </h1>
    <h2 style="color: #fc0404c2; font-size: 25px;"> El nombre es : {{apellido}} </h2>
     {% for x in  numeros %}
            {% if x <= 3 %}
            <p style="color : red;"> Es un mal numero : {{x}} </p>
            {% else%}
            <p style="color: green;"> Es un excelente numero : {{x}}</p>
            {% endif %}
        {% endfor %}
</body>
</html>